server:
  port: 9001
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 5s
    threads:
      max: 20
      min-spare: 5
spring:
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/bookshop_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5

  application:
    name: catalog-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:9002
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false
      retry:
        max-attempts: 5
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
management:
  endpoints:
    web:
      exposure:
        include: refresh
