apiVersion: v1
kind: Service
metadata:
  name: authorization-server
  labels:
    app: authorization-server
spec:
  type: ClusterIP
  selector:
    app: authorization-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9005
