server:
  port: 9005
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 5s
    threads:
      max: 20
      min-spare: 5

spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:9002
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false
      retry:
        max-attempts: 5
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  application:
    name: authorization-server
  lifecycle:
    timeout-per-shutdown-phase: 15s

management:
  endpoints:
    web:
      exposure:
        include: refresh
logging:
  level:
    org.springframework.security: trace