server:
  port: 9002
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YoussefAgagg/config-repo
          default-label: master
          clone-on-start: true
          timeout: 5
          force-pull: true
